# Generated by Django 5.0.4 on 2024-04-29 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("p", "Pending"), ("a", "Accepted"), ("d", "Declined"), ("c", "Cancelled")],
                        default="p",
                        max_length=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "attended",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="user.user"
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="event.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Приглашения",
                "verbose_name_plural": "Приглашения",
            },
        ),
    ]
