# Generated by Django 5.0.4 on 2024-05-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_created_user_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created",
        ),
        migrations.RemoveField(
            model_name="user",
            name="modified",
        ),
    ]
