# Generated by Django 5.0.4 on 2024-05-16 12:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Backlog"),
                            (2, "Todo"),
                            (3, "In Progress"),
                            (4, "In review"),
                            (5, "Release"),
                            (6, "Done"),
                            (7, "Cancelled"),
                        ],
                        default=1,
                        verbose_name="Task status",
                    ),
                ),
                ("start", models.DateTimeField(blank=True, null=True, verbose_name="Start")),
                ("end", models.DateTimeField(blank=True, null=True, verbose_name="End")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(None, "No priority"), (1, "High"), (2, "Medium"), (3, "Low")],
                        null=True,
                        verbose_name="Task priority",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "default_related_name": "tasks",
            },
        ),
    ]
