# Generated by Django 5.0.4 on 2024-05-16 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(("start__lt", models.F("end"))), name="tasks_task_end_gt_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("end__isnull", True), ("start__isnull", True)),
                    models.Q(("end__isnull", False), ("start__isnull", False)),
                    _connector="OR",
                ),
                name="tasks_task_end_start_both_or_none",
            ),
        ),
    ]
