# Generated by Django 5.0.4 on 2024-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_task_created_at_remove_task_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(default="some", max_length=50, verbose_name="Title"),
            preserve_default=False,
        ),
    ]
