# Generated by Django 5.0.4 on 2024-05-16 12:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="Description")),
                ("start", models.DateTimeField(verbose_name="Start")),
                ("end", models.DateTimeField(verbose_name="End")),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "default_related_name": "events",
            },
        ),
    ]
