# Generated by Django 5.0.4 on 2024-05-03 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_created_event_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="created",
        ),
        migrations.RemoveField(
            model_name="event",
            name="modified",
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name="Created"),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name="Updated"),
        ),
    ]
