# Generated by Django 5.0.4 on 2024-04-29 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=250, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[("d", "Done"), ("todo", "Todo"), ("inprogress", "Inprogress")],
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("start", models.DateField(blank=True, verbose_name="Начало")),
                ("end", models.DateField(blank=True, verbose_name="Окончание")),
                (
                    "priority",
                    models.CharField(
                        choices=[("p", "Prymary"), ("s", "Secondary")], max_length=1, verbose_name="Приоритет"
                    ),
                ),
                (
                    "author",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_tasks",
                        to="user.user",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
