# Generated by Django 5.0.4 on 2024-05-16 12:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_event_created_at_remove_event_updated_at_and_more"),
        ("invitations", "0005_remove_invitation_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("attendee", "event")},
        ),
    ]
